config/routes.rb
# frozen_string_literal: true

# This file is part of SSID.
#
# SSID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SSID is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with SSID.  If not, see <http://www.gnu.org/licenses/>.

SSID::Application.routes.draw do
  resources :submission_logs

  get 'assignments/:id/submission_similarities/guest_user',
      to: 'submission_similarities#create_guest_user',
      as: 'guest_user_create'

  get 'assignments/:assignment_id/submission_similarities/:submission_similarity_id/guest_user',
      to: 'submission_logs#view_similarity',
      as: 'guest_view_similarity'

  # Login/Logout routes
  devise_scope :user do
    get 'cover' => 'users/sessions#index'
    get 'guide' => 'users/sessions#guide'

    authenticated :user do
      root to: 'announcements#index', as: :authenticated_root
    end

    root to: 'users/sessions#index'
  end

  devise_for :users, controllers: {
    # :registrations => "users/registrations",
    # :sign_in => "users/sessions",
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  resources :announcements

  namespace :admin do
    resources :users do
      get 'approve' => 'users#approve', :as => 'approve_user'
      put 'update' => 'users#upgrade_to_admin_account'
    end
  end

  resources :courses do
    get 'status'
    get 'cluster_students', defaults: { format: 'json' }

    resources :user_course_memberships

    resources :assignments do
      get 'log' => 'assignments#show_log'
      get 'list' => 'submissions#index'
    end

    get 'visualize/' => 'visualize#index'
    get 'visualize/similarity_cluster_graph' => 'visualize#similarity_cluster_graph'
    get 'visualize/similarity_cluster_table' => 'visualize#similarity_cluster_table'
    get 'visualize/top_similar_submissions' => 'visualize#top_similar_submissions'
  end

  resources :assignments do
    get 'cluster_students', defaults: { format: 'json' }
    get 'view_printable_multiple' => 'submission_similarities#view_printable_multiple'

    resources :cluster_groups, controller: 'submission_cluster_groups'

    resources :submission_similarities do
      put 'confirm_as_plagiarism' => 'submission_similarities#confirm_as_plagiarism'
      put 'suspect_as_plagiarism' => 'submission_similarities#suspect_as_plagiarism'
      put 'unmark_as_plagiarism' => 'submission_similarities#unmark_as_plagiarism'
      get 'view_printable' => 'submission_similarities#view_printable'
    end

    resources :submissions do
      get 'log' => 'submission_logs#index'
    end
  end

  # ajax calls
  resources :submission_similarities do
    resources :submissions do
      put 'mark_as_guilty' => 'submissions#mark_as_guilty'
      put 'mark_as_not_guilty' => 'submissions#mark_as_not_guilty'
    end
  end

  resources :cluster_groups, controller: 'submission_cluster_groups' do
    resources :clusters, controller: 'submission_clusters'
  end

  get 'clusters/show_for_submission_ids' => 'submission_clusters#show_for_submission_ids', defaults: { format: 'json' }
  get 'clusters/ids_and_group_ids_for_student_ids' => 'submission_clusters#ids_and_group_ids_for_student_ids',
      defaults: { format: 'json' }
  get 'clusters/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/show_ranking_partial' => 'submission_clusters#show_ranking_partial'

  get 'clusters/:id' => 'submission_clusters#show', defaults: { format: 'json' }
  get 'clusters/:id/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/:id/show_table_partial' => 'submission_clusters#show_table_partial'

  resources :students, controller: 'users' do
    get 'submission_similarities/show_table_partial' => 'submission_similarities#show_table_partial'
  end

  namespace :api do
    namespace :v1 do
      # Assignments routes
      resources :assignments, only: [] do
        resources :submission_similarities, only: %i[index show] do
          member do
            get 'view_pdf'
          end
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :courses, controller: 'courses' do
        resources :assignments, controller: 'assignments'
      end
    end
  end
end

app/controllers/courses_controller.rb
=begin
This file is part of SSID.

SSID is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SSID is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with SSID.  If not, see <http://www.gnu.org/licenses/>.
=end

class CoursesController < ApplicationController
  before_action { |controller|
    controller.send :authenticate_actions_for_admin, only: [ :destroy ]
  }
  before_action { |controller|
    if params[:course_id]
      @course = Course.find(params[:course_id])
    elsif params[:id]
      @course = Course.find(params[:id])
    end
    if @course
      controller.send :authenticate_actions_for_role, UserCourseMembership::ROLE_TEACHING_STAFF,
                                                      course: @course,
                                                      only: [ :index, :cluster_students , :status ]
      controller.send :authenticate_actions_for_role, UserCourseMembership::ROLE_TEACHING_ASSISTANT,
                                                      course: @course,
                                                      only: [ :index, :cluster_students , :status ]
      controller.send :authenticate_actions_for_role, UserCourseMembership::ROLE_STUDENT,
                                                      course: @course,
                                                      only: [ :index ]
    end
  }
  
  # GET /courses/1/status
  def status
    @course = Course.find(params[:course_id])
    @empty_assignments = @course.empty_assignments
    @processing_assignments = @course.processing_assignments
    @processed_assignments = @course.processed_assignments
    @erroneous_assignments = @course.erroneous_assignments
  end

  # GET /courses
  def index
    @courses = current_user.is_admin ? Course.all : current_user.courses
  end

  # GET /courses/new
  def new
    @course = Course.new
    expiry_time = Time.now.getutc
    expiry_date = expiry_time.to_date
    @course.expiry = DateTime.new(expiry_date.year + 1, expiry_date.month, expiry_time.mday, expiry_time.hour, expiry_time.min)
  end

  # POST /courses
  def create
    @course = Course.new { |c|
      c.code = params[:course]["code"]
      c.name = params[:course]["name"]
      c.academic_year = params[:course]["academic_year"]
      c.semester = params[:course]["semester"]

      expiry_time = DateTime.parse(params[:course]["expiry"])
      expiry_date = expiry_time.to_date
      c.expiry = Time.zone.local_to_utc(DateTime.new(expiry_date.year, expiry_date.month, expiry_date.mday, expiry_time.hour, expiry_time.min))
    }

    if @course.valid? and @course.save
    else
      render action: "new"
      return
    end

    @membership = UserCourseMembership.new { |m|
      m.user = current_user
      m.course = @course
      m.role = UserCourseMembership::ROLE_TEACHING_STAFF
    }

    if @membership.valid? && @membership.save
      redirect_to courses_url, notice: 'Course was successfully created.'
    else
      render action: 'new'
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # PUT /courses/1
  def update
    @course = Course.find(params[:id])
    @course.code = params[:course]["code"]
    @course.name = params[:course]["name"]
    @course.academic_year = params[:course]["academic_year"]
    @course.semester = params[:course]["semester"]

    expiry_time = DateTime.parse(params[:course]["expiry"])
    expiry_date = expiry_time.to_date
    @course.expiry = Time.zone.local_to_utc(DateTime.new(expiry_date.year, expiry_date.month, expiry_date.mday, expiry_time.hour, expiry_time.min))
    
    if @course.errors.empty? and @course.save
      redirect_to courses_url, notice: 'Course was successfully updated.'
    else
      render action: "new"
    end
  end

  # DELETE /courses/1
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_url, notice: 'Course was successfully deleted.'
  end

  # GET /courses/1/cluster_students
  def cluster_students
    respond_to do |format|
      format.json { 
        render json: @course.cluster_students.collect { |s| 
          { id: s.id, name: s.name } 
        } 
      }
    end
  end

end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div>
      <h6 class="error_title"><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h6>
      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-12">
      <%= f.label :code, class: "form-label" %>
      <%= f.text_field :code, class: "form-control" %>
    </div>
    <div class="col-12">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-sm-6">
      <%= f.label :academic_year, class: "form-label" %>
      <%= f.select :academic_year, Course.options_for_academic_year, {}, { :class => 'form-select' } %>
    </div>
    <div class="col-sm-6">
      <%= f.label :semester, class: "form-label" %>
      <%= f.select :semester, [1, 2], {}, { :class => 'form-select' } %>
    </div>
    <div class="col-12">
      <%= f.label :expiry, class: "form-label" %>
      <%= f.datetime_field :expiry, class: "form-control" %>
    </div>
    <div class="col-12">
      <%= f.submit class: "submit" %>
    </div>
  </div>
<% end %>


app/views/courses/edit.html.erb
<div class="col-md-6">
<h4>Edit Course</h4>

<%= render 'form' %>
</div>

app/views/courses/index.html.erb
<%#
This file is part of SSID.

SSID is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SSID is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with SSID.  If not, see <http://www.gnu.org/licenses/>.
%>
<header class="course_header">
  <h4>Courses</h4>
  <%= link_to image_tag("add_circle_outline_blue_24dp.svg", size: "28", alt: "New Course"), new_course_url, {'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'New Course'} %>
</header>

<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th class="course_code">Code</th>
      <th class="course_name">Name</th>
      <th class="course_year_sem">Academic Year (Semester)</th>
      <th class="course_role">Your Role</th>
      <% unless current_user.is_admin %>
        <th class="course_assignments_col">Assignments</th>
      <% end %>
      <th>View</th>
      <% if current_user.is_admin %>
        <th class="course_other_actions">Actions</th>
      <% end %>      
    </tr>
  </thead>
  <tbody>
<% if @courses.empty? %>
  <tr>
    <td colspan="7">No courses</td>
  </tr>
<% else %>
  <% @courses.each { |course| %>
  <tr>
    <td><%= course.code %></td>
    <td><%= course.name %></td>
    <td><%= course.academic_year %> Semester <%= course.semester %></td>
    <td><%= course.role_string_for_user(current_user) %></td>
    <% unless current_user.is_admin %>
      <td><%= course.assignments.size %></td>
    <% end %>
    <td class="course_view_actions">
      <%= link_to image_tag("assignment_black_24dp.svg", alt: "Assignments"), course_assignments_url(course), { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Assignments' } %>
      <%= link_to image_tag("people_black_24dp.svg", alt: "Users"), course_user_course_memberships_url(course), {'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Users'} %>
      <%= link_to image_tag("show_chart_black_24dp.svg", alt: "Visuals"), course_visualize_url(course), {'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Visuals'} %>
    </td>
    <% if current_user.is_admin %>   
      <td>
        <div class="dropdown">
          <a data-toggle="dropdown" id="courseDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag("more_vert_black_24dp.svg", alt: "Course Menu Dropdown")%>
          </a>
          <ul class="dropdown-menu" aria-labelledby="courseDropdownMenuLink"> 
            <li><%= link_to "Edit", edit_course_url(course), :class => 'dropdown-item' %></li>
            <li>
              <%= button_tag 'Delete', class: "dropdown-item", data: { 'bs-toggle' => "modal", 'bs-target' => "#deleteCourseModal", 'bs-url' => "#{course_url(course)}" } %>
            </li>
          </ul> 
        </div>

      </td>
    <% end %>

  </tr>
  <% } %>
<% end %>
  </tbody>
</table>

<div class="modal fade" id="deleteCourseModal" tabindex="-1" role="dialog" aria-hidden="true">
  <% @modal = SiteModal.new("Delete Module", "This module will be permanently deleted and cannot be recovered. Are you sure?", { :name => "OK", :method => :delete }) %>
  <%= render partial: "site/modal", locals: { modal: @modal }%>
</div>

<%= javascript_include_tag "site_modal.js" %>

app/views/courses/new.html.erb
<div class="col-md-6">
  <h4>New Course</h4>

  <%= render 'form' %>
</div>

app/views/courses/status.html.erb
<% unless @erroneous_assignments.empty? %>
    <h3>Erroneous:</h3>
    <table class="erroneous_assignments">
      <thead>
        <tr>
          <th>Title</th>
          <th class="lang_col">Language</th>
          <th class="submitted_on_col">Submitted On</th>
          <th class="action_col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @erroneous_assignments.each { |a| %>
      <tr>
        <td><%= a.title %></td>
        <td><%= a.language_string %></td>
        <td><%= a.submission_similarity_process.created_at.in_time_zone %></td>
        <td>
          <%= link_to "View upload log", course_assignment_log_url(@course, a) %>
          <%= link_to "Delete", course_assignment_url(@course, a), method: "delete", class: "last", confirm: "Delete assignment?" %>
        </td>
      </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>
  
  <% unless @empty_assignments.empty? %>
    <h3>Empty (yet to submit file for uploading):</h3>
    <table class="empty_assignments">
      <thead>
        <tr>
          <th>Title</th>
          <th class="lang_col">Language</th>
          <th class="submitted_on_col">Submitted On</th>
          <th class="action_col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @empty_assignments.each { |a| %>
        <tr>
          <td><%= a.title %></td>
          <td><%= a.language_string %></td>
          <td><%= a.created_at.in_time_zone %></td>
          <td>
            <%= link_to "Upload submission", course_assignment_url(@course, a) %>
            <%= link_to "Delete", course_assignment_url(@course, a), method: "delete", class: "last", confirm: "Delete assignment?" %>
          </td>
        </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>
  
  <% unless @processing_assignments.empty? %>
    <h3>Processing:</h3>
    <table class="processing_assignments">
      <thead>
        <tr>
          <th>Title</th>
          <th class="lang_col">Language</th>
          <th class="submitted_on_col">Submitted On</th>
          <th class="action_col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @processing_assignments.each { |a| %>
        <tr>
          <td><%= a.title %></td>
          <td><%= a.language_string %></td>
          <td><%= a.created_at.in_time_zone %></td>
          <td class="processing"><em>Processing...</em></td>
        </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>
  

  <% unless @processed_assignments.empty? %>
    <% unless @erroneous_assignments.empty? and @processing_assignments.empty? %>
      <h3>Processed:</h3>
    <% end %>
    <table class="processed_assignments">
      <thead>
        <tr>
          <th>Title</th>
          <th class="lang_col">Language</th>
          <th class="submissions_col">Submissions</th>
          <th class="suspected_cases_col">Suspected Plagiarism Cases</th>
          <th class="marked_cases_col">Confirmed Plagiarism Cases</th>
          <th class="action_col">View</th>
          <th class="delete_col"></th>
        </tr>
      </thead>
      <tbody>
      <% @processed_assignments.each { |a| %>
      <tr>
        <td><%= a.title %></td>
        <td><%= a.language_string %></td>
        <td><%= a.submissions.size %></td>
        <td><%= a.suspected_plagiarism_cases.size %></td>
        <td><%= a.confirmed_plagiarism_cases.size %></td>
        <td>
          <%= link_to "Submission similarities", assignment_submission_similarities_url(a) %>
          <%= link_to "Similarity groups", assignment_cluster_groups_url(a) %>
          <%= link_to "Upload log", course_assignment_log_url(@course, a), class: "last" %>
        </td>
        <td>
          <%= link_to "Delete", course_assignment_url(@course, a), method: "delete", class: "last", confirm: "Delete assignment?" %>
        </td>
      </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>

app/views/courses/status.js.erb
  <% unless @erroneous_assignments.empty? %>
    <h5>Erroneous</h5>
    <table class="erroneous_assignments">
      <thead>
        <tr>
          <th>Title</th>
          <th class="lang_col">Language</th>
          <th class="submitted_on_col">Submitted On</th>
          <th>View</th>
          <th class="action_col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @erroneous_assignments.each { |a| %>
      <tr>
        <td><%= a.title %></td>
        <td><%= a.language_string %></td>
        <td><%= a.submission_similarity_process.created_at.in_time_zone %></td>
        <td> 
          <%= link_to image_tag("description_black_24dp.svg", alt: "Upload log"), course_assignment_log_url(@course, a), { 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Upload log' } %>
        </td>
        <td>
          <div class="dropdown">
            <a data-toggle="dropdown" id="erroneousAssignmentDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <%= image_tag("more_vert_black_24dp.svg", alt: "Erroneous Assignment Menu Dropdown")%>      
            </a>
            <ul class="dropdown-menu" aria-labelledby="erroneousAssignmentDropdownMenuLink">
              <li>
                <%= button_tag 'Delete', class: "dropdown-item", data: { 'bs-toggle' => "modal", 'bs-target' => "#deleteAssignmentModal", 'bs-url' => "#{course_assignment_url(@course, a)}" } %>
              </li>
            </ul>
          </div>        
        </td>
      </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>
  
  <% unless @empty_assignments.empty? %>
    <h5>Empty (yet to submit file for uploading)</h5>
    <table class="empty_assignments">
      <thead>
        <tr>
          <th>Title</th>
          <th class="lang_col">Language</th>
          <th class="submitted_on_col">Submitted On</th>
          <th class="action_col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @empty_assignments.each { |a| %>
        <tr>
          <td><%= a.title %></td>
          <td><%= a.language_string %></td>
          <td><%= a.created_at.in_time_zone %></td>
          <td>
            <div class="dropdown">
              <a data-toggle="dropdown" id="emptyAssignmentDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag("more_vert_black_24dp.svg", alt: "Empty Assignment Menu Dropdown")%>                      
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Upload submission", course_assignment_url(@course, a), class: "dropdown-item" %></li>
                <li>
                  <%= button_tag 'Delete', class: "dropdown-item", data: { 'bs-toggle' => "modal", 'bs-target' => "#deleteAssignmentModal", 'bs-url' => "#{course_assignment_url(@course, a)}" } %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>
  
  <% unless @processing_assignments.empty? %>
    <h5>Processing</h5>
    <table class="processing_assignments">
      <thead>
        <tr>
          <th>Title</th>
          <th class="lang_col">Language</th>
          <th class="submitted_on_col">Submitted On</th>
          <th class="action_col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @processing_assignments.each { |a| %>
        <tr>
          <td><%= a.title %></td>
          <td><%= a.language_string %></td>
          <td><%= a.created_at.in_time_zone %></td>
          <td class="processing"><em>Processing...</em></td>
        </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>
  

  <% unless @processed_assignments.empty? %>
    <% unless @erroneous_assignments.empty? and @processing_assignments.empty? %>
      <h5>Processed</h5>
    <% end %>
    <table class="processed_assignments">
      <thead>
        <tr>
          <th class="col-3">Title</th>
          <th class="lang_col col-1">Language</th>
          <th class="submissions_col col-1">Submissions</th>
          <th class="suspected_cases_col col-2">Suspected Cases</th>
          <th class="marked_cases_col col-2">Confirmed Cases</th>
          <th class="col-2">View</th>
          <th class="assignment_other_actions col-1">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @processed_assignments.each { |a| %>
      <tr>
        <td><%= a.title %></td>
        <td><%= a.language_string %></td>
        <td><%= a.submissions.size %></td>
        <td><%= a.suspected_plagiarism_cases.size %></td>
        <td><%= a.confirmed_plagiarism_cases.size %></td>
        <td class="assignment_view_actions">
          <%= link_to image_tag("plagiarism_black_24dp.svg", alt: "Submission similarities"), assignment_submission_similarities_url(a), { 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Submission similarities' } %>
          <%= link_to image_tag("scatter_plot_black_24dp.svg", alt: "Similarity groups"), assignment_cluster_groups_url(a), { 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Similarity groups'} %>
          <%= link_to image_tag("description_black_24dp.svg", alt: "Upload log"), course_assignment_log_url(@course, a), { 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'Upload log' } %>
        </td>
        <td>
          <div class="dropdown">
            <a data-toggle="dropdown" id="processedAssignmentDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <%= image_tag("more_vert_black_24dp.svg", alt: "Assignment Menu Dropdown")%>      
            </a>
            <ul class="dropdown-menu" aria-labelledby="processedAssignmentDropdownMenuLink">
              <li>
                <%= button_tag 'Delete', class: "dropdown-item", data: { 'bs-toggle' => "modal", 'bs-target' => "#deleteAssignmentModal", 'bs-url' => "#{course_assignment_url(@course, a)}" } %>
              </li>
            </ul>
          </div>
        </td>
      </tr>
      <% } %>
      </tbody>
    </table>
  <% end %>

  <div class="modal fade" id="deleteAssignmentModal" tabindex="-1" role="dialog" aria-hidden="true">
    <% @modal = SiteModal.new("Delete Assignment", "This assignment will be permanently deleted and cannot be recovered. Are you sure?", { :name => "OK", :method => :delete }) %>
    <%= render partial: "site/modal", locals: { modal: @modal }%>
  </div>
    
  <%= javascript_include_tag "site_modal.js" %>