config/routes.rb
# frozen_string_literal: true

# This file is part of SSID.
#
# SSID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SSID is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with SSID.  If not, see <http://www.gnu.org/licenses/>.

SSID::Application.routes.draw do
  resources :submission_logs

  get 'assignments/:id/submission_similarities/guest_user',
      to: 'submission_similarities#create_guest_user',
      as: 'guest_user_create'

  get 'assignments/:assignment_id/submission_similarities/:submission_similarity_id/guest_user',
      to: 'submission_logs#view_similarity',
      as: 'guest_view_similarity'

  # Login/Logout routes
  devise_scope :user do
    get 'cover' => 'users/sessions#index'
    get 'guide' => 'users/sessions#guide'

    authenticated :user do
      root to: 'announcements#index', as: :authenticated_root
    end

    root to: 'users/sessions#index'
  end

  devise_for :users, controllers: {
    # :registrations => "users/registrations",
    # :sign_in => "users/sessions",
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  resources :announcements

  namespace :admin do
    resources :users do
      get 'approve' => 'users#approve', :as => 'approve_user'
      put 'update' => 'users#upgrade_to_admin_account'
    end
  end

  resources :courses do
    get 'status'
    get 'cluster_students', defaults: { format: 'json' }

    resources :user_course_memberships

    resources :assignments do
      get 'log' => 'assignments#show_log'
      get 'list' => 'submissions#index'
    end

    get 'visualize/' => 'visualize#index'
    get 'visualize/similarity_cluster_graph' => 'visualize#similarity_cluster_graph'
    get 'visualize/similarity_cluster_table' => 'visualize#similarity_cluster_table'
    get 'visualize/top_similar_submissions' => 'visualize#top_similar_submissions'
  end

  resources :assignments do
    get 'cluster_students', defaults: { format: 'json' }
    get 'view_printable_multiple' => 'submission_similarities#view_printable_multiple'

    resources :cluster_groups, controller: 'submission_cluster_groups'

    resources :submission_similarities do
      put 'confirm_as_plagiarism' => 'submission_similarities#confirm_as_plagiarism'
      put 'suspect_as_plagiarism' => 'submission_similarities#suspect_as_plagiarism'
      put 'unmark_as_plagiarism' => 'submission_similarities#unmark_as_plagiarism'
      get 'view_printable' => 'submission_similarities#view_printable'
    end

    resources :submissions do
      get 'log' => 'submission_logs#index'
    end
  end

  # ajax calls
  resources :submission_similarities do
    resources :submissions do
      put 'mark_as_guilty' => 'submissions#mark_as_guilty'
      put 'mark_as_not_guilty' => 'submissions#mark_as_not_guilty'
    end
  end

  resources :cluster_groups, controller: 'submission_cluster_groups' do
    resources :clusters, controller: 'submission_clusters'
  end

  get 'clusters/show_for_submission_ids' => 'submission_clusters#show_for_submission_ids', defaults: { format: 'json' }
  get 'clusters/ids_and_group_ids_for_student_ids' => 'submission_clusters#ids_and_group_ids_for_student_ids',
      defaults: { format: 'json' }
  get 'clusters/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/show_ranking_partial' => 'submission_clusters#show_ranking_partial'

  get 'clusters/:id' => 'submission_clusters#show', defaults: { format: 'json' }
  get 'clusters/:id/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/:id/show_table_partial' => 'submission_clusters#show_table_partial'

  resources :students, controller: 'users' do
    get 'submission_similarities/show_table_partial' => 'submission_similarities#show_table_partial'
  end

  namespace :api do
    namespace :v1 do
      # Assignments routes
      resources :assignments, only: [] do
        resources :submission_similarities, only: %i[index show] do
          member do
            get 'view_pdf'
          end
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :courses, controller: 'courses' do
        resources :assignments, controller: 'assignments'
      end
    end
  end
end

app/helpers/site_helper.rb
=begin
This file is part of SSID.

SSID is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SSID is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with SSID.  If not, see <http://www.gnu.org/licenses/>.
=end

module SiteHelper
  private

  def highlight_if_current(url)
    current_url = %Q{http://#{request.env['SERVER_NAME']}#{request.env['REQUEST_URI']}}

    if current_url == url
      %Q{ class="highlight"}.html_safe
    else
      ""
    end
  end

  def link_to_unless_current(name, url)
    current_url = %Q{http://#{request.env['SERVER_NAME']}#{request.env['REQUEST_URI']}}

    ((current_url == url) ? "<span>#{name}</span>" : link_to(name, url)).html_safe
  end
end

app/views/site/_breadcrumb.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Courses", courses_path %></li> 
  <% if controller_name == "courses" %>
    <% if action_name == "new" or action_name == "create" %>
      <li class="breadcrumb-item">New Course</li>
    <% elsif action_name == "edit" or action_name == "update" %>
      <li class="breadcrumb-item">Edit Course</li>
    <% end %>
  <% elsif controller_name == "user_course_memberships" %>
      <li class="breadcrumb-item"><%= link_to "#{course.code} Users", course_user_course_memberships_url(course) %></li>
  <% elsif controller_name == "visualize" %>
      <li class="breadcrumb-item"><%= link_to "#{course.code} Visualizations", course_visualize_url(course) %></li>
    <% if action_name != "index" %>
      <li class="breadcrumb-item"><%= action_name.humanize.titleize %></li>
    <% end %>
  <% elsif course  %>
    <li class="breadcrumb-item"><%= link_to "#{course.code} Assignments", course_assignments_url(course) %></li>
  <% end %>
  <% if assignment %>
    <% if controller_name == "assignments" %>
      <% if action_name == "new" or action_name == "create" %>
        <li class="breadcrumb-item">New Assignment</li>
      <% elsif action_name == "edit" or action_name == "update" %>
        <li class="breadcrumb-item">Edit Assignment</li>
      <% elsif action_name == "show_log" %>
        <li class="breadcrumb-item"><%= %Q{Assignment: #{assignment.title} Upload Log} %></li>
      <% end %>
    <% elsif controller_name == "submission_similarities" %>
      <li class="breadcrumb-item"><%= link_to %Q{Assignment: #{assignment.title} Submission Similarities}, assignment_submission_similarities_url(assignment) %></li>
      <% if action_name == "show" %>
      <li class="breadcrumb-item">Submissions from Student <%= submission_similarity.student1.name %> and <%= submission_similarity.student2.name %></li>
      <% end %>
    <% elsif controller_name == "submission_logs" %>
      <li class="breadcrumb-item"><%= %Q{Assignment: #{assignment.title} Submission Log for Student #{submission.student_name}} %></li>
    <% end %>
  <% end %>
  <% if controller_name == "submission_cluster_groups" or controller_name == "submission_clusters" %>
    <li class="breadcrumb-item"><%= link_to "Assignment: #{assignment.title} Submission Cluster Groups", assignment_cluster_groups_url(@assignment) %></li>
    <% if action_name == "new" or action_name == "create" %>
      <li class="breadcrumb-item">New Submission Cluster Group</li>
    <% end %>
  <% end %>
  <% if controller_name == "submission_clusters" %>
    <li class="breadcrumb-item">Cluster Group (Cut-Off Criterion = <%= @submission_cluster_group.cut_off_criterion %>%)</li>
  <% end %>
</ol>

app/views/site/_modal.html.erb
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content rounded-4">
    <div class="modal-header border-bottom-0">
      <h5 class="modal-title" id="modalTitle"><%= @modal.title %></h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body pt-0">
      <%= @modal.supporting_text %>
    </div>
    <div class="modal-footer pt-0 border-top-0">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
      <%= button_to @modal.primary_action[:name], "", :method => @modal.primary_action[:method], :class => "btn btn-primary" %>
    </div>
  </div>
</div>

<script>
  /* Remove action url when cancel action is triggered */
  $(".btn-close").click((event) => {
    $(".modal-footer > .button_to").attr("action", "");
  })

  $(".btn-secondary").click((event) => {
    $(".modal-footer > .button_to").attr("action", "");
  })
</script>