config/routes.rb
# frozen_string_literal: true

# This file is part of SSID.
#
# SSID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SSID is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with SSID.  If not, see <http://www.gnu.org/licenses/>.

SSID::Application.routes.draw do
  resources :submission_logs

  get 'assignments/:id/submission_similarities/guest_user',
      to: 'submission_similarities#create_guest_user',
      as: 'guest_user_create'

  get 'assignments/:assignment_id/submission_similarities/:submission_similarity_id/guest_user',
      to: 'submission_logs#view_similarity',
      as: 'guest_view_similarity'

  # Login/Logout routes
  devise_scope :user do
    get 'cover' => 'users/sessions#index'
    get 'guide' => 'users/sessions#guide'

    authenticated :user do
      root to: 'announcements#index', as: :authenticated_root
    end

    root to: 'users/sessions#index'
  end

  devise_for :users, controllers: {
    # :registrations => "users/registrations",
    # :sign_in => "users/sessions",
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  resources :announcements

  namespace :admin do
    resources :users do
      get 'approve' => 'users#approve', :as => 'approve_user'
      put 'update' => 'users#upgrade_to_admin_account'
    end
  end

  resources :courses do
    get 'status'
    get 'cluster_students', defaults: { format: 'json' }

    resources :user_course_memberships

    resources :assignments do
      get 'log' => 'assignments#show_log'
      get 'list' => 'submissions#index'
    end

    get 'visualize/' => 'visualize#index'
    get 'visualize/similarity_cluster_graph' => 'visualize#similarity_cluster_graph'
    get 'visualize/similarity_cluster_table' => 'visualize#similarity_cluster_table'
    get 'visualize/top_similar_submissions' => 'visualize#top_similar_submissions'
  end

  resources :assignments do
    get 'cluster_students', defaults: { format: 'json' }
    get 'view_printable_multiple' => 'submission_similarities#view_printable_multiple'

    resources :cluster_groups, controller: 'submission_cluster_groups'

    resources :submission_similarities do
      put 'confirm_as_plagiarism' => 'submission_similarities#confirm_as_plagiarism'
      put 'suspect_as_plagiarism' => 'submission_similarities#suspect_as_plagiarism'
      put 'unmark_as_plagiarism' => 'submission_similarities#unmark_as_plagiarism'
      get 'view_printable' => 'submission_similarities#view_printable'
    end

    resources :submissions do
      get 'log' => 'submission_logs#index'
    end
  end

  # ajax calls
  resources :submission_similarities do
    resources :submissions do
      put 'mark_as_guilty' => 'submissions#mark_as_guilty'
      put 'mark_as_not_guilty' => 'submissions#mark_as_not_guilty'
    end
  end

  resources :cluster_groups, controller: 'submission_cluster_groups' do
    resources :clusters, controller: 'submission_clusters'
  end

  get 'clusters/show_for_submission_ids' => 'submission_clusters#show_for_submission_ids', defaults: { format: 'json' }
  get 'clusters/ids_and_group_ids_for_student_ids' => 'submission_clusters#ids_and_group_ids_for_student_ids',
      defaults: { format: 'json' }
  get 'clusters/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/show_ranking_partial' => 'submission_clusters#show_ranking_partial'

  get 'clusters/:id' => 'submission_clusters#show', defaults: { format: 'json' }
  get 'clusters/:id/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/:id/show_table_partial' => 'submission_clusters#show_table_partial'

  resources :students, controller: 'users' do
    get 'submission_similarities/show_table_partial' => 'submission_similarities#show_table_partial'
  end

  namespace :api do
    namespace :v1 do
      # Assignments routes
      resources :assignments, only: [] do
        resources :submission_similarities, only: %i[index show] do
          member do
            get 'view_pdf'
          end
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :courses, controller: 'courses' do
        resources :assignments, controller: 'assignments'
      end
    end
  end
end

app/controllers/admin/users_controller.rb
=begin
This file is part of SSID.

SSID is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SSID is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with SSID.  If not, see <http://www.gnu.org/licenses/>.
=end

class Admin::UsersController < ApplicationController

  before_action :is_admin, only: [:index, :approve, :upgrade_to_admin_account, :destroy]

  # GET /admin/users
  def index
    @admins = User.where(is_admin: true)
    @students = User.joins(:courses, :memberships).where(users: { is_admin_approved: false}).where(user_course_memberships: { role: UserCourseMembership::ROLE_STUDENT })
    @signups = User.where(is_admin_approved: false) - @students

    # users don't belong to any course
    @loners = User.all - User.joins(:memberships) - @admins - @signups
  end  

  def approve
    @the_user = User.find(params[:user_id])
    @the_user.update_attribute(:is_admin_approved, true)
    @the_user.save
    UserMailer.admin_approved(@the_user).deliver_now
    redirect_to admin_users_url, notice: 'User was successfully approved.'
  end

  def upgrade_to_admin_account
    @the_user = User.find(params[:user_id])
    @the_user.update_attribute(:is_admin, true)
    @the_user.save
    logger.info("#{Time.now} Account id #{@the_user.id} was upgraded to admin by #{current_user.id}")
    redirect_to admin_users_url, notice: 'User was successfully upgraded to admin account.'    
  end
  
  # TODO: refactor later
  # DELETE /admin/users/1
  # DELETE /admin/users/1?course_id=1
  def destroy
    @the_user = User.find(params[:id])

    # Check if we are destroying the membeship, not the user
    if params[:course_id]
      course = Course.find(params[:course_id])
      
      # see whether the user to be deleted is a guest user
      membership = course.membership_for_user(@the_user)
      guest = course.guest_user_finder(@the_user)
      
      # Redirect current user back to the course users page
      url = course_users_url(course)
      
      if membership && membership.role == UserCourseMembership::ROLE_GUEST && guest.destroy && membership.destroy 
        redirect_to url, notice: "User was removed from #{course.code}."
      elsif membership && membership.role != UserCourseMembership::ROLE_STUDENT && membership.destroy
        redirect_to url, notice: "User was removed from #{course.code}."
      else
        redirect_to url, alert: "Error removing user"
      end
    else
      if @the_user.is_admin
        if @the_user.destroy
          redirect_to admin_users_url, notice: 'User was successfully deleted.'
        else
          redirect_to admin_users_url, alert: @the_user.errors.to_a.join(", ")
        end
      else
        if @the_user.destroy
          redirect_to admin_users_url, notice: 'User was successfully deleted.'
        else
          redirect_to admin_users_url, alert: @the_user.errors.to_a.join(", ")
        end
      end
    end
  end

  protected

  def is_admin
    unless current_user.is_admin
      redirect_to root_url, status: 401
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super

  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
    user = User.from_omniauth(auth)
    # byebug
    if user.present?
      found_user = User.find_by(email: auth.info.email)
      if found_user.present?
        if found_user.is_admin_approved?
          sign_out_all_scopes
          flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect user, event: :authentication
        else
          redirect_to new_user_session_url, alert: "Your account is still being processed."
        end
      else
        user.name = user.full_name
        user.confirm
        user.save
        redirect_to root_url, notice: "Welcome to SSID! Your account is being processed. An email will be sent to you once your account is approved."
      end
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end
  protected
  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
  private
  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name, :full_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :full_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  
  skip_before_action :authenticate_user!, only: [:new, :create, :index, :guide]

  def index
    render "layouts/cover"
  end

  def new
    super
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user and user.valid_password?(params[:user][:password]) and user.is_admin_approved
      if user.confirmed?
        sign_in user
        redirect_to root_url
      else
        redirect_to new_user_session_url, alert: "Your account is not activated. Please check your email for the activation link."
      end
    else
      redirect_to new_user_session_url, alert: "Invalid user/password combination or user account is still being processed."
    end
  end


  def destroy
    sign_out current_user
    redirect_to root_url
  end

  def guide
    render "layouts/guide"
  end

  protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
  # end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/views/admin/users/index.html.erb
<h4>Users</h4>
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="admin_users_section"> 
<header class="user_header">
<h5>Admins</h5>
</header>

<table>
  <thead>
    <tr>
      <th>Full Name</th>
      <th class="id_col">Login</th>
      <th class="actions_col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each { |admin| %>
      <tr>
        <td><%= admin.full_name || "--" %><%= " <em>(This is you)</em>".html_safe if @user == admin %></td>
        <td><%= admin.name %></td>
        <td>
          <div class="dropdown">
            <a data-toggle="dropdown" id="adminUserDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <%= image_tag("more_vert_black_24dp.svg", alt: "Admin User Menu Dropdown")%>            
            </a>
            <ul class="dropdown-menu" aria-labelledby="adminUserDropdownMenuLink">
              <% if admin == @user %>
                <li><%= link_to "Settings", edit_user_url(@user), class: "dropdown-item" %></li>
              <% else %>
                <!-- TODO -->
                <!--
                <li><%= link_to "Edit", edit_admin_user_url(admin), class: "dropdown-item" %></li>
                <li>
                  <%= button_tag 'Delete', class: "dropdown-item", data: { 'bs-toggle' => "modal", 'bs-target' => "#deleteUserModal", 'bs-url' => "#{admin_user_url(admin)}" } %>
                </li>
                -->
              <% end %>
            </ul>
          </div>
        </td>
      </tr>
    <% } %>
  </tbody>
</table>

</div>

<% unless @loners.empty? %>
<div class="lone_users_section">

  <h5>Users With No Course Membership</h5>

  <table>
    <thead>
      <tr>
        <th>Full Name/ Hash</th>
        <th class="id_col">Login/ Hash</th>
        <th class="actions_col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @loners.each { |user| %>
        <tr>
          <td><%= user.full_name || "--" %></td>
          <td><%= user.name %></td>
          <td>
            <div class="dropdown">
              <a data-toggle="dropdown" id="loneUserDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag("more_vert_black_24dp.svg", alt: "Lone Users Menu Dropdown")%>        
              </a>
              <ul class="dropdown-menu" aria-labelledby="loneUserDropdownMenuLink">
                <!-- TODO 
                <li><%= link_to "Edit", edit_admin_user_url(user), class: 'dropdown-item' %></li>
                <li>
                  <%= button_tag 'Delete', class: "dropdown-item", data: { 'bs-toggle' => "modal", 'bs-target' => "#deleteUserModal", 'bs-url' => "#{admin_user_url(user)}" } %>
                </li>
                -->
              </ul>
            </div>
          </td>          
        </tr>
      <% } %>
    </tbody>
  </table>
</div>
<% end %>

<% unless @signups.empty? %>
<div class="new_users_section">

  <h5>New User Signups</h5>

  <table>
    <thead>
      <tr>
        <th>Full Name/ Hash</th>
        <th class="id_col">Login/ Hash</th>
        <th class="actions_col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @signups.each { |user| %>
        <tr>
          <td><%= user.full_name || "--" %></td>
          <td><%= user.name %></td>
          <td>
            <div class="dropdown">
              <a data-toggle="dropdown" id="loneUserDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag("more_vert_black_24dp.svg", alt: "Lone Users Menu Dropdown")%>        
              </a>
              <ul class="dropdown-menu" aria-labelledby="loneUserDropdownMenuLink">
                <!-- TODO
                <li><%= link_to "Edit", edit_admin_user_url(user), class: 'dropdown-item' %></li>
                <li>
                  <%= button_tag 'Delete', class: "dropdown-item", data: { 'bs-toggle' => "modal", 'bs-target' => "#deleteUserModal", 'bs-url' => "#{admin_user_url(user)}" } %>
                </li>
                <li>
                -->
                  <li><%= link_to "Upgrade to admin account", admin_user_update_url(user), method: "put", data: {confirm: "The user will be upgraded to admin account. Are you sure?"}, class: 'dropdown-item' %></li>            
                  <li><%= link_to "Approve", admin_user_approve_user_url(user), class: 'dropdown-item' %></li>
                </li>
              </ul>
            </div>
          </td>          
        </tr>
      <% } %>
    </tbody>
  </table>
</div>
<% end %>

<div class="modal fade" id="deleteUserModal" tabindex="-1" role="dialog" aria-hidden="true">
  <% @modal = SiteModal.new("Delete User", "The user will be permanently deleted. Are you sure?", { :name => "OK", :method => :delete }) %>
  <%= render partial: "site/modal", locals: { modal: @modal }%>
</div>


<%= javascript_include_tag "site_modal.js" %>