config/routes.rb
# frozen_string_literal: true

# This file is part of SSID.
#
# SSID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SSID is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with SSID.  If not, see <http://www.gnu.org/licenses/>.

SSID::Application.routes.draw do
  resources :submission_logs

  get 'assignments/:id/submission_similarities/guest_user',
      to: 'submission_similarities#create_guest_user',
      as: 'guest_user_create'

  get 'assignments/:assignment_id/submission_similarities/:submission_similarity_id/guest_user',
      to: 'submission_logs#view_similarity',
      as: 'guest_view_similarity'

  # Login/Logout routes
  devise_scope :user do
    get 'cover' => 'users/sessions#index'
    get 'guide' => 'users/sessions#guide'

    authenticated :user do
      root to: 'announcements#index', as: :authenticated_root
    end

    root to: 'users/sessions#index'
  end

  devise_for :users, controllers: {
    # :registrations => "users/registrations",
    # :sign_in => "users/sessions",
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  resources :announcements

  namespace :admin do
    resources :users do
      get 'approve' => 'users#approve', :as => 'approve_user'
      put 'update' => 'users#upgrade_to_admin_account'
    end
  end

  resources :courses do
    get 'status'
    get 'cluster_students', defaults: { format: 'json' }

    resources :user_course_memberships

    resources :assignments do
      get 'log' => 'assignments#show_log'
      get 'list' => 'submissions#index'
    end

    get 'visualize/' => 'visualize#index'
    get 'visualize/similarity_cluster_graph' => 'visualize#similarity_cluster_graph'
    get 'visualize/similarity_cluster_table' => 'visualize#similarity_cluster_table'
    get 'visualize/top_similar_submissions' => 'visualize#top_similar_submissions'
  end

  resources :assignments do
    get 'cluster_students', defaults: { format: 'json' }
    get 'view_printable_multiple' => 'submission_similarities#view_printable_multiple'

    resources :cluster_groups, controller: 'submission_cluster_groups'

    resources :submission_similarities do
      put 'confirm_as_plagiarism' => 'submission_similarities#confirm_as_plagiarism'
      put 'suspect_as_plagiarism' => 'submission_similarities#suspect_as_plagiarism'
      put 'unmark_as_plagiarism' => 'submission_similarities#unmark_as_plagiarism'
      get 'view_printable' => 'submission_similarities#view_printable'
    end

    resources :submissions do
      get 'log' => 'submission_logs#index'
    end
  end

  # ajax calls
  resources :submission_similarities do
    resources :submissions do
      put 'mark_as_guilty' => 'submissions#mark_as_guilty'
      put 'mark_as_not_guilty' => 'submissions#mark_as_not_guilty'
    end
  end

  resources :cluster_groups, controller: 'submission_cluster_groups' do
    resources :clusters, controller: 'submission_clusters'
  end

  get 'clusters/show_for_submission_ids' => 'submission_clusters#show_for_submission_ids', defaults: { format: 'json' }
  get 'clusters/ids_and_group_ids_for_student_ids' => 'submission_clusters#ids_and_group_ids_for_student_ids',
      defaults: { format: 'json' }
  get 'clusters/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/show_ranking_partial' => 'submission_clusters#show_ranking_partial'

  get 'clusters/:id' => 'submission_clusters#show', defaults: { format: 'json' }
  get 'clusters/:id/show_graph_partial' => 'submission_clusters#show_graph_partial'
  get 'clusters/:id/show_table_partial' => 'submission_clusters#show_table_partial'

  resources :students, controller: 'users' do
    get 'submission_similarities/show_table_partial' => 'submission_similarities#show_table_partial'
  end

  namespace :api do
    namespace :v1 do
      # Assignments routes
      resources :assignments, only: [] do
        resources :submission_similarities, only: %i[index show] do
          member do
            get 'view_pdf'
          end
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :courses, controller: 'courses' do
        resources :assignments, controller: 'assignments'
      end
    end
  end
end

app/models/submission_cluster_group.rb
=begin
This file is part of SSID.

SSID is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SSID is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with SSID.  If not, see <http://www.gnu.org/licenses/>.
=end

class SubmissionClusterGroup < ActiveRecord::Base
  # SubmissionClusterGroup#cut_off_criterion_type Constants
  TYPE_CONFIRMED_OR_SUSPECTED_PLAGIARISM_CRITERION = 0
  TYPE_CONFIRMED_PLAGIARISM_CRITERION = 1
  TYPE_USER_DEFINED_CRITERION = 2
  TYPE_STRINGS = [
    "Confirmed or Suspected Plagiarism Cases",
    "Confirmed Plagiarism Cases",
    "User-Defined Value"
  ]

  # SubmissionClusterGroup#description Constants
  DESCRIPTIONS = {
    TYPE_CONFIRMED_OR_SUSPECTED_PLAGIARISM_CRITERION => "Based on cases confirmed or suspected as plagiarism",
    TYPE_CONFIRMED_PLAGIARISM_CRITERION => "Based on cases confirmed as plagiarism",
    TYPE_USER_DEFINED_CRITERION => "Based on user-defined cut-off criterion"
  }

  has_many :clusters, class_name: "SubmissionCluster", :dependent => :delete_all
  belongs_to :assignment

  validates_presence_of :assignment_id
  validates_numericality_of :cut_off_criterion, allow_nil: false, allow_blank: false, greater_than: 0, less_than_or_equal_to: 100
  validates_uniqueness_of :cut_off_criterion, scope: [:assignment_id, :cut_off_criterion], :message => "has already been created"

  def cluster_ids
    self.clusters.collect { |c| c.id }
  end
end

app/controllers/submission_cluster_groups_controller.rb
=begin
This file is part of SSID.

SSID is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SSID is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with SSID.  If not, see <http://www.gnu.org/licenses/>.
=end

class SubmissionClusterGroupsController < ApplicationController
  before_action { |controller|
    if params[:assignment_id]
      @assignment = Assignment.find(params[:assignment_id])
      @course = @assignment.course
      controller.send :authenticate_actions_for_role, UserCourseMembership::ROLE_TEACHING_ASSISTANT,
                                                      course: @course,
                                                      only: [ :index, :new, :create ]
      controller.send :authenticate_actions_for_role, UserCourseMembership::ROLE_STUDENT,
                                                      course: @course,
                                                      only: [ ]
      controller.send :authenticate_actions_for_role, UserCourseMembership::ROLE_GUEST,
                                                      course: @course,
                                                      only: [ ]
    end
  }

  # GET /assignments/1/cluster_groups
  def index
    @cluster_groups = @assignment.submission_cluster_groups
  end

  # GET /assignments/1/cluster_groups/new
  def new
    @assignment_plagiarism_cases = []
    @assignment_plagiarism_cases[SubmissionClusterGroup::TYPE_CONFIRMED_OR_SUSPECTED_PLAGIARISM_CRITERION] =
      @assignment.suspected_plagiarism_cases + @assignment.confirmed_plagiarism_cases
    @assignment_plagiarism_cases[SubmissionClusterGroup::TYPE_CONFIRMED_PLAGIARISM_CRITERION] =
      @assignment.confirmed_plagiarism_cases
    @submission_cluster_group = SubmissionClusterGroup.new
  end

  # POST /assignments/1/cluster_groups
  def create
    # Determine cut-off criterion if type requires
    if params[:submission_cluster_group]["cut_off_criterion_type"] == SubmissionClusterGroup::TYPE_CONFIRMED_OR_SUSPECTED_PLAGIARISM_CRITERION.to_s
      params[:submission_cluster_group]["cut_off_criterion"] = @assignment.confirmed_or_suspected_plagiarism_cases.collect { |submission_similarity|
        submission_similarity.similarity
      }.min
    elsif params[:submission_cluster_group]["cut_off_criterion_type"] == SubmissionClusterGroup::TYPE_CONFIRMED_PLAGIARISM_CRITERION.to_s
      params[:submission_cluster_group]["cut_off_criterion"] = @assignment.confirmed_plagiarism_cases.collect { |submission_similarity|
        submission_similarity.similarity
      }.min
    end

    @submission_cluster_group = SubmissionClusterGroup.new { |scg|
      scg.cut_off_criterion_type = params[:submission_cluster_group]["cut_off_criterion_type"]
      scg.cut_off_criterion = params[:submission_cluster_group]["cut_off_criterion"]
      scg.description = SubmissionClusterGroup::DESCRIPTIONS[params[:submission_cluster_group]["cut_off_criterion_type"].to_i]
      scg.assignment_id = @assignment.id
    }
    
    # Run java program if @submission_cluster_group is valid
    if @submission_cluster_group.valid?
      require 'submissions_handler'
      
      # Rollback if clustering error
      error_message = ""
      @submission_cluster_group.transaction do
        @submission_cluster_group.save
        begin
          SubmissionsHandler.process_cluster_group(@submission_cluster_group)
          redirect_to assignment_cluster_groups_url(@assignment), notice: 'Submission cluster group was successfully created.'
        rescue Exception => e
          error_message = e.message
          raise ActiveRecord::Rollback
        end
      end

      # Render #new and display errors
      unless @submission_cluster_group.id
        @assignment_plagiarism_cases = []
        @assignment_plagiarism_cases[SubmissionClusterGroup::TYPE_CONFIRMED_OR_SUSPECTED_PLAGIARISM_CRITERION] =
          @assignment.suspected_plagiarism_cases + @assignment.confirmed_plagiarism_cases
        @assignment_plagiarism_cases[SubmissionClusterGroup::TYPE_CONFIRMED_PLAGIARISM_CRITERION] =
          @assignment.confirmed_plagiarism_cases
        @submission_cluster_group.errors.add :base, error_message
        render action: "new" 
      end
    else
      @assignment_plagiarism_cases = []
      @assignment_plagiarism_cases[SubmissionClusterGroup::TYPE_CONFIRMED_OR_SUSPECTED_PLAGIARISM_CRITERION] =
        @assignment.suspected_plagiarism_cases + @assignment.confirmed_plagiarism_cases
      @assignment_plagiarism_cases[SubmissionClusterGroup::TYPE_CONFIRMED_PLAGIARISM_CRITERION] =
        @assignment.confirmed_plagiarism_cases
      render action: "new"
    end
  end

  # DELETE /assignments/1/cluster_groups/1
  def destroy
    @submission_cluster_group = SubmissionClusterGroup.find(params[:id])
    @submission_cluster_group.destroy

    redirect_to assignment_cluster_groups_url(@assignment), notice: 'Submission cluster group was successfully deleted.'
  end
end

app/views/submission_cluster_groups/_form.html.erb
<%= form_for([@assignment, @submission_cluster_group], url: assignment_cluster_groups_path) do |f| %>
  <% if @submission_cluster_group.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@submission_cluster_group.errors.count, "error") %> prohibited this submission cluster group from being saved:</h5>
      <ul>
      <% @submission_cluster_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    Create the cluster group with a cut-off criterion...
    <% SubmissionClusterGroup::TYPE_STRINGS.each_with_index { |type, type_idx| %>
      <% if type_idx == SubmissionClusterGroup::TYPE_CONFIRMED_OR_SUSPECTED_PLAGIARISM_CRITERION or 
           type_idx == SubmissionClusterGroup::TYPE_CONFIRMED_PLAGIARISM_CRITERION %>
        <% disabled = "disabled" if @assignment_plagiarism_cases[type_idx].empty? %>
        <div><label <%= %Q{ class="disabled"}.html_safe if disabled %>>
        <%= f.radio_button :cut_off_criterion_type, type_idx, 
                            checked: @submission_cluster_group.cut_off_criterion_type == type_idx,
                            onclick: "SubmissionClusterGroup.disableUserDefinedTextField();", 
                            disabled: disabled %>
        To include all currently <%= type %>
      <% elsif type_idx == SubmissionClusterGroup::TYPE_USER_DEFINED_CRITERION %>
        <div><label>
        <%= f.radio_button :cut_off_criterion_type, type_idx, 
                          checked: @submission_cluster_group.cut_off_criterion_type == type_idx,
                          onclick: "SubmissionClusterGroup.enableUserDefinedTextField();"%>
        With a <%= type %> of: <%= f.text_field :cut_off_criterion %> %
      <% end %>
      </label></div>
    <% } %>
  </div>
  <div class="notes">
    The cut-off criterion provides a threshold value for the cluster group. Any submission cluster with a maximum similarity value lower than the threshold will not be included in the cluster group. Cut-off criterion values to include all currently confirmed or suspected plagiarism cases are computed automatically once submission similarities have been marked as confirmed or suspected for plagiarism.
  </div>
  <div>
    <%= f.submit class: "submit" %>
  </div>
<% end %>

app/views/submission_cluster_groups/index.html.erb
<div class="submission_cluster_group_header">
<h4>Assignment: <%= @assignment.title %> Submission Cluster Groups</h4>
<div class="actions">
  <%= link_to image_tag("add_circle_outline_blue_24dp.svg", size: "28", alt: "New Cluster Group"), new_assignment_cluster_group_url(@assignment), { "data-toggle" => "tooltip", "data-placement" => "bottom", "title" => "New Cluster Group" } %>
</div>
</div>
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if @cluster_groups.empty? %>
  <p class="none_created">No cluster group has been created.<br />
  Cluster groups allow you to identify clusters of students with submission similarity values above a defined threshold.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Cut-Off Criterion</th>
        <th>Number of Clusters</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @cluster_groups.each { |cluster_group| %>
        <tr>
          <td><%= cluster_group.cut_off_criterion %></td>
          <td><%= cluster_group.clusters.size %></td>
          <td>[Created on <%= cluster_group.created_at.in_time_zone %>] <%= cluster_group.description %></td>
          <td>
            <div class="dropdown">
              <a data-toggle="dropdown" id="clusterGroupDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag("more_vert_black_24dp.svg", alt: "Cluster Group Dropdown Menu Link")%>
              </a>
              <ul class="dropdown-menu">
                <!-- <li><%= link_to "View Clusters", cluster_group_clusters_url(cluster_group), class: "dropdown-item" %></li> -->
                <li>
                  <%= button_tag "Delete", class: "dropdown-item", data: { "bs-toggle" => "modal", "bs-target" => "#deleteClusterGroupModal", 'bs-url' => "#{assignment_cluster_group_url(@assignment, cluster_group)}" } %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% } %>
    </tbody>
  </table>

  <div class="modal fade" id="deleteClusterGroupModal" tabindex="-1" role="dialog" aria-hidden="true">
    <% @modal = SiteModal.new("Delete Cluster Group", "This cluster group will be permanently deleted and cannot be recovered. Are you sure?", { :name => "OK", :method => :delete }) %>
    <%= render partial: "site/modal", locals: { modal: @modal }%>
  </div>
<% end %>

<%= javascript_include_tag("site_modal.js") %>

app/views/submission_cluster_groups/new.html.erb
<h4>New Submission Cluster Group</h4>

<%= render 'form' %>